/*
 * Vesktop, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2023 Vendicated and Vencord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "./patches/tray";
import "./patches/equicordSupportBanner";
import "./patches/devBadge";
import "./patches/tempMute";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import { VoiceActions } from "@equicord/types/webpack/common";

import HyprcordPlugins from "./components/settings/HyprcordPlugins";
import SettingsUi from "./components/settings/Settings";
import { VesktopLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

import type SettingsPlugin from "@equicord/types/plugins/_core/settings";
import { VesktopSettingsIcon } from "shared/icons";

VesktopLogger.log("if you read this you are a LARP");
VesktopLogger.log(`Equibop v${VesktopNative.app.getVersion()}`);

const { customEntries, customSections } = Vencord.Plugins.plugins.Settings as any as typeof SettingsPlugin;

customEntries.push({
    key: "equicord_equibop_settings",
    title: "Hyprcord Settings",
    Component: SettingsUi,
    Icon: VesktopSettingsIcon
});

customEntries.push({
    key: "equicord_hyprcord_plugins",
    title: "Hyprcord Plugins",
    Component: HyprcordPlugins,
    Icon: VesktopSettingsIcon
});

customSections.push(() => ({
    section: "HyprcordSettings",
    label: "Hyprcord Settings",
    element: SettingsUi,
    className: "vc-equibop-settings"
}));

customSections.push(SectionTypes => ({
    section: SectionTypes.PLUGINS ?? "Plugins",
    label: "Hyprcord Plugins",
    element: HyprcordPlugins,
    className: "vc-hyprcord-plugins"
}));

VesktopNative.voice.onToggleSelfMute(() => VoiceActions.toggleSelfMute());
VesktopNative.voice.onToggleSelfDeaf(() => VoiceActions.toggleSelfDeaf());

// TODO: remove this legacy workaround once some time has passed
if (!Vencord.Api.Styles.vencordRootNode) {
    const style = document.createElement("style");
    style.id = "vesktop-css-core";
    VesktopNative.app.getRendererCss().then(css => (style.textContent = css));
    document.addEventListener("DOMContentLoaded", () => document.documentElement.append(style), { once: true });
}
